### ISSUE TITLE
DEV Remove newly added generic masterIntegrations and masterIntegrationFields from table

### ISSUE THREAD

**Issue by Riturajcse** [Shippable/base#1036]
https://github.com/Shippable/pm/issues/7813
https://github.com/Shippable/pm/issues/7822
https://github.com/Shippable/pm/issues/7824
https://github.com/Shippable/pm/issues/7826

List of masterInts to be removed
- slackCreds
- emailCreds
- hipchatCreds
- sshKeys

**Comment by ankunath** [comment]
all the new masterIntegrations(redundant) are removed from alpha, and the `alias` column is dropped.
