### ISSUE TITLE
DEV 7934 add enforcePrivateJobQuota, technicalSupportAvailable, customNodesAdminOnly to systemConfigs

### ISSUE THREAD

**Issue by Bharath92** [Shippable/base#1097]
https://github.com/Shippable/pm/issues/7934

**Comment by Bharath92** [comment]
verified in alpha, closing

**Comment by ric03uec** [comment]
@Bharath92 reopening this. im getting the following error when trying to upgrade local installation

![image](https://cloud.githubusercontent.com/assets/1110988/23369622/d889f1c8-fcc6-11e6-8eaf-e12238956620.png)

**Comment by ric03uec** [comment]
works after adding new fields from state file example
@Bharath92 the steps for this are not updated in release doc. please add them and close this issue.

**Comment by Bharath92** [comment]
updated the release docs, closing
