### ISSUE TITLE
7840.2 DEV remove nodeScriptsLocation

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#1133]
- https://github.com/Shippable/pm/issues/7840
- remove `nodeScriptsLocation` from system config 
- remove the fields from state file and state file example
- remove all associated code that sets this field
- Add the following environment variable to API: NODE_SCRIPTS_LOCATION=/home/shippable/scripts/node

**Comment by stephanielingwood** [comment]
verified in rc
