### ISSUE TITLE
7840.5 DEV remove `ini` artifacts

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#1134]
- https://github.com/Shippable/pm/issues/7840
- since `ini` microservice is no longer in use, remove all artifacts for ini
  - entry from versions file
  - code to bring up ini
  - ini queue from rootQueue list

**Comment by stephanielingwood** [comment]
verified in rc - the rootQueueList no longer has micro.ini in it, and ini was not updated in the last rc deployment.
