### ISSUE TITLE
BUG 6636 API stops responding erratically

### ISSUE THREAD

**Issue by shrivara** [Shippable/base#155]
After a first install, the API stops responding sometimes on further installs.
https://github.com/Shippable/pm/issues/6636

**Comment by ric03uec** [comment]
lets add `--update-delay 10` to the `./base.sh --upgrade <service>` command. i faced this too and adding  a delay helped fix the problem.
im not sure of the exact reason why this is happening though
also, moving forward, we should use installer to upgrade the services and get rid of the scripts
