### ISSUE TITLE
BUG 6636 copying files to local fails

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#181]
- https://github.com/Shippable/pm/issues/6636
- we cannot assume that users will run the command with `sudo ./base.install...` . right now all functions that copy files locally fail with permission denied. the functions needs to handle this correctly

![image](https://cloud.githubusercontent.com/assets/1110988/18321202/d5f23aaa-74e1-11e6-8c44-752ba31aa2f9.png)

**Comment by shrivara** [comment]
Dup https://github.com/Shippable/base/issues/94
