### ISSUE TITLE
6636 DEV backup statefile

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#185]
- https://github.com/Shippable/pm/issues/6636
- before running any functions in `main` section of any of the scripts, backup statefile to `data/state.json.backup`
- this will make sure that if the function fails and messes up the statefile, we are able to recover the system using state file backup
- add state file backup in gitignore

**Comment by ric03uec** [comment]
@Bharath92 @shrivara is this complete ?

**Comment by shrivara** [comment]
This is done.
