### ISSUE TITLE
DEV 6884 Read from state.json instead of config.json

### ISSUE THREAD

**Issue by shrivara** [Shippable/base#357]
Remove all references to config.json and read from state.json instead. This is a substantial change and will need the following:
- Replace  `state.json.example` with `config.json.example`
- Remove references of copying state from `config.json` to `state.json`
- Keep references of reading from state file
- The user will be expected to update `state.json`.

https://github.com/Shippable/pm/issues/6884

**Comment by ric03uec** [comment]
this is complete, closing
