### ISSUE TITLE
DEV 6884 Create complete versions.json with a reference release

### ISSUE THREAD

**Issue by shrivara** [Shippable/base#359]
- ~~With the current state of release, create a versions.json with complete details. Ie. https://gist.github.com/ric03uec/dda235b4c07aa1c6228cddded5bcab75~~
- ~~Add this in `/versions`. Also, add the current state of `migrations.sql` in `/migrations`.~~
- ~~From this point on, any new migration should be accompanied with a new version.~~
- the versions file in the folder `versions/` should have all the components and their mappings on shippable

https://github.com/Shippable/pm/issues/6884

**Comment by trriplejay** [comment]
1. integrationServices
  - go through the list of masterIntegrations. for each one, add it to the `integrationServices` list.
  - for each one, add a `services` list.  This is a list of the shippable services that are required to use the integration. (api, for exmaple, should appear in every single one).  Use the two existing as an example.  
  - It is OK for the same service to appear in multiple integrations
2. serviceConfigs
  - this is a list of each unique shippable service, combined with the ENVs required to start it, as well as the default number of replicas that should be run.  Make sure every shippable service is represented in this list.
