### ISSUE TITLE
DEV 6636 Make vault installation more robust

### ISSUE THREAD

**Issue by kanthchandra** [Shippable/base#36]
from https://github.com/Shippable/pm/issues/6636#issuecomment-243622281

**Comment by kanthchandra** [comment]
```
not sure where is vault init being done. the vault bootstrap script is too fragile right now and keeps failing without any errors. this needs to be more robust

    check for keys file. if its present then it means vault has been initialized
    check sealed/unsealed status from vault status output and not just the return code

```

**Comment by ric03uec** [comment]
@Bharath92 this is happening a lot now. im not able to initialize vault cleanly anytime adn the script fails with some error or the other
e.g.
![image](https://cloud.githubusercontent.com/assets/1110988/18227541/ac1344de-71dc-11e6-90ce-13a1ec89cd48.png)
in this case, vault was running, db was up and tables were created but the bootstrap vault script failed

**Comment by Bharath92** [comment]
We are getting this error because we are calling vault status before calling vault init. We need to call vault status, so that we know from its exit code whether the vault is sealed, unsealed or not uninitialized. Based on the exit code we conitnue with the further steps for vault.

**Comment by ric03uec** [comment]
fixed, closing this
