### ISSUE TITLE
DEV 6884 Selectively install components

### ISSUE THREAD

**Issue by shrivara** [Shippable/base#362]
- Based on the list of required `masterIntegrations` from `state.json`, the installer needs to select the components that need to be installed.
- The service should be installed if its not already available in `state.json`
- The service should be updated if its already available in `state.json`
- This should pick the version.json based on `release` field in `state.json`.

https://github.com/Shippable/pm/issues/6884

**Comment by Bharath92** [comment]
@ric03uec @shrivara Based on the masterIntegrations we have to add services in the  the _manageServices.sh file. But some of the masterIntegrations like auth, scm dont have services.  So, should only the notification and payment masterIntegrations be added to the services array in the state.json file in _manageServices.sh?
