### ISSUE TITLE
DEV 6884 Selectively remove components

### ISSUE THREAD

**Issue by shrivara** [Shippable/base#364]
- Based on the list of required `masterIntegrations` from `state.json`, the installer needs to select the components that need to be installed.
- Go throught the list of services installed at the end of services installation.
- Remove the ones which shouldn't be installed
- This should pick the version.json based on `release` field in `state.json`.

https://github.com/Shippable/pm/issues/6884

**Comment by manishas** [comment]
why isn't this closed?
