### ISSUE TITLE
DEV 6884.1 remove systemMachineImage data insert from migrations

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#398]
- https://github.com/Shippable/pm/issues/6884
- migrations is inserting a default system machine image, that should be removed
- any new system machine image should be provided in versions file and installer should upsert the value from there

**Comment by ric03uec** [comment]
@shrivara @Bharath92 not sure how this is closed without addressing the second point in the issue

**Comment by shrivara** [comment]
I was going to do it as part of https://github.com/Shippable/base/issues/397

**Comment by ric03uec** [comment]
ok
