### ISSUE TITLE
6884 BUG. gitlab users not getting created after login

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#431]
- https://github.com/Shippable/pm/issues/6884
- after a successful install of the system, gitlab groups need to be created for the subscriptions. this is not happening either on local or server installation

**Comment by Bharath92** [comment]
@ric03uec This was probably happening because Git store masterIntegration wasn't added in state.json

**Comment by ric03uec** [comment]
@Bharath92 its happening after ive added the integration. are we even trying to run installer from scratch to try to reproduce the problem. i can repro this every single time i run installer from ground up so im not sure why we're still guessing the causes of this. 

![image](https://cloud.githubusercontent.com/assets/1110988/19402351/8e579f5e-9215-11e6-9f8b-102be13a123e.png)

**Comment by ric03uec** [comment]
this is fixed, closing
