### ISSUE TITLE
6684 BUG login fails after first run

### ISSUE THREAD

**Issue by ric03uec** [Shippable/base#446]
- https://github.com/Shippable/pm/issues/6884

- for bbs, the first login fails with following error
![image](https://cloud.githubusercontent.com/assets/1110988/19407051/09e9c7d4-924b-11e6-8193-8d55c96f2e7b.png)
- running installer again without any changes fixes this

**Comment by shrivara** [comment]
This happens when providers are added after the API has initialized. The reinstall fixes the problem as API get initialized again. Added a fix for this in local.

**Comment by shrivara** [comment]
Didn't test this in production mode, but there is a restart API method present. Please reopen if your see this again.
