### ISSUE TITLE
7095 DEV update jobDependencies and subscriptionIntegrationPermissions to use the convention routeObject/:routeObjectId

### ISSUE THREAD

**Issue by ankul-shippable** [Shippable/base#770]
https://github.com/Shippable/api/issues/16249

**Comment by mohit5it9** [comment]
verified in alpha and qhode.shippable
for **subscriptionIntegrationPermissions**:

![pr](https://cloud.githubusercontent.com/assets/11424742/20561437/ac68fe9e-b1a4-11e6-8dd2-22afe092a7b4.png)

for **jobDependencies**:

![pr1](https://cloud.githubusercontent.com/assets/11424742/20561481/dc7b1914-b1a4-11e6-8f2c-bb02243de939.png)
