### ISSUE TITLE
7547.3 Add Kubernetes master Integration

### ISSUE THREAD

**Issue by scriptnull** [Shippable/base#884]
https://github.com/Shippable/pm/issues/7547 

```
displayName: Kubernetes
name: KUBERNETES
type: deploy
level: account
typeCode: refer latest migration file
```
masterIntegrationFields are as follows: 

| Field Name | Description | type | isRequired | isSecure | Default value |
|:---------------:|:---------------:|:------:|:--------------:|:-------------:|:-----------------:|
| clusterAccessType | MASTER_NODE or BASTION_HOST | string | true | false | MASTER_NODE |
| masterKubeConfigContent | contents of kubeconfig file | string | false | true | - |
| bastionHostIP | IP address of  bastion node | string | false | false | - |
| bastionKubeConfigType | DEFAULT or PATH or CONTENT | string | true | false | DEFAULT |
| (Don't Implement) bastionKubeConfigPath | File path of [kubeconfig file](http://kubernetes.io/docs/user-guide/kubeconfig-file/) in bastion host | string | false |  false | - |
| bastionKubeConfigContent | Contents of [kubeconfig file](http://kubernetes.io/docs/user-guide/kubeconfig-file/) to be used | string | false | true | - |
| bastionPublicKey | public key used by Shippable to access master or bastion node | string | false | false | - |
| bastionPrivateKey | private key used by Shippable to access master or bastion node | string | false | true | - |

**Comment by jatindogra** [comment]
This is completed and verified in alpha.shippable.com.
