### ISSUE TITLE
DEV 7498.14 Update base installer to stop all stateless services before upgrading

### ISSUE THREAD

**Issue by nranjanShippable** [Shippable/base#892]
https://github.com/Shippable/pm/issues/7498

STEPS:
1. Stop all the stateless services
2. Upgrade the statefull services
3. Upgrade the stateles services.

**Comment by deepikasl** [comment]
@avinci: @ric03uec: 

Currently for upgrading services, we are removing each service and bringing them back from scratch. 

For doing issue steps: we have to upgrade each service by checking whether it is running or not. This will change the flow of `provisionServices`. Is this what required?

**Comment by ric03uec** [comment]
@avinci im not able to understand the scenario we're trying to support with this change.
as of now, these are the steps being followed by the installer
  - figure out which services to run based on enabled master integrations
  - boot services that need to be run with the new version
  - bring down old services and services that should not be run

doing the suggested changes actually will ensure that microservices always have the latest sytemConfig values. we can design the workflow if this indeed is the scenario.

**Comment by avinci** [comment]
There are 2 kinds of services, the ones that are customer facing and the ones that are not.

1. first check if all the installer pre-reqs are good. this includes images, pull them verify the integrity of the installer files, figure out what needs to happen in terms of master integrations etc. So now all decisions have been taken and the only thing left is to upgrade.
1. Now stop all non customer facing services in 1 shot. 
1. Add all the new metadata etc needed, including migrations etc.
1. Now upgrade customer facing services
1. Now bring up non customer facing services based on the new state
1. remove all the old images
1. end installer

**Comment by deepikasl** [comment]
This is done.
